#!/bin/bash

sudo apt-get update
sudo apt-get install -y unzip

curl -Lo aws-sam-cli-linux-x86_64.zip \
  https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip

unzip -o aws-sam-cli-linux-x86_64.zip -d sam-installation

sudo ./sam-installation/install

sam --version
