AWSTemplateFormatVersion: '2010-09-09'
Description: 'creates an IAM role with SSM and KMS permissions for EC2 instances, including a custom KMS decrypt policy and instance profile, with unique resource names based on the stack name to avoid naming collisions.'

Resources:
  # KMS Decrypt Policy for SSM
  myKMSDecryptPolicyForSSM:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'myKMSDecryptPolicyForSSM-${AWS::StackName}'
      Description: 'Allows KMS decrypt and generate data key operations for SSM'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'

  # EC2 SSM Role for Private Instance Demo
  myEC2SSMRolePrivateInstanceDemo:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'myEC2_SSMRolePrivateInstanceDemo-${AWS::StackName}'
      Description: 'Allows EC2 instances to call AWS services like CloudWatch and Systems Manager on your behalf. Used for private EC2 instance demo to connect to SSM'
      Path: '/'
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - !Ref myKMSDecryptPolicyForSSM

  # Instance Profile for EC2 instances
  myEC2SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub 'myEC2_SSMRolePrivateInstanceDemo-${AWS::StackName}'
      Roles:
        - !Ref myEC2SSMRolePrivateInstanceDemo

Outputs:
  RoleArn:
    Description: 'ARN of the created IAM role'
    Value: !GetAtt myEC2SSMRolePrivateInstanceDemo.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'
  
  InstanceProfileArn:
    Description: 'ARN of the created instance profile'
    Value: !GetAtt myEC2SSMInstanceProfile.Arn
    Export:
      Name: !Sub '${AWS::StackName}-InstanceProfileArn'
  
  RoleName:
    Description: 'Name of the created IAM role'
    Value: !Ref myEC2SSMRolePrivateInstanceDemo
    Export:
      Name: !Sub '${AWS::StackName}-RoleName'
